"""empty message

Revision ID: 4198779d0400
Revises: cca94d15af7a
Create Date: 2019-07-23 14:15:48.229427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4198779d0400'
down_revision = 'cca94d15af7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'slug')
    op.drop_column('bucketlists', 'slug')
    # ### end Alembic commands ###
